name: Java CI/CD with Gradle

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build -x test
        shell: bash

      - name: Upload Build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            build/libs/*.jar

  deploy:
    name: CD with SCP and SSH
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Install sshpass and SSH client
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass openssh-client

      - name: SCP JAR to EC2
        run: |
          sshpass -p ${{ secrets.EC2_PASSWORD }} scp -o StrictHostKeyChecking=no build/libs/*.jar ${{ secrets.EC2_USER_DEV }}@${{ secrets.EC2_HOST_DEV }}:/home/ubuntu/app/

      - name: Deploy application on EC2
        run: |
          sshpass -p ${{ secrets.EC2_PASSWORD }} ssh -T -o StrictHostKeyChecking=no ${{ secrets.EC2_USER_DEV }}@${{ secrets.EC2_HOST_DEV }} << 'EOF'
            sudo systemctl start redis-server
            sudo fuser -k -n tcp 8080 || true
            sleep 10
            
            # 환경 변수를 사용해 애플리케이션 실행
            sudo nohup java -jar /home/ubuntu/app/*.jar \
              --spring.datasource.url=${{ secrets.RDS_URL }} \
              --spring.datasource.username=${{ secrets.RDS_USERNAME }} \
              --spring.datasource.password=${{ secrets.RDS_PASSWORD }} \
              --cloud.aws.credentials.access-key=${{ secrets.AWS_ACCESS_KEY }} \
              --cloud.aws.credentials.secret-key=${{ secrets.AWS_SECRET_KEY }} \
              --jwt.secret=${{ secrets.JWT_SECRET }} \
              > /home/ubuntu/app/nohup.out 2>&1 &
            
            sudo lsof -i tcp:8080
          EOF
